<?php

return [

    'POST_SLUG'                => env('POST_SLUG'),
    'SIDEBAR_POST_COUNT'       => env('SIDEBAR_POST_COUNT'),
    'WASABI_BUCKET_NAME'       => env('WASABI_BUCKET_NAME'),
    'HOMEPAGE_POST_COUNT'      => env('HOMEPAGE_POST_COUNT'),
    'RANDOM_POST_START_COUNT'  => env('RANDOM_POST_START_COUNT'),
    'RANDOM_POST_END_COUNT'    => env('RANDOM_POST_END_COUNT'),
    'HOMEPAGE_POST_PAGINATION' => env('HOMEPAGE_POST_PAGINATION'),
    'THEME_NAME'               => env('THEME_NAME'),
    'GOOGLE_SEARCH'            => env('GOOGLE_SEARCH'),
    'SEARCH_INPUT_TEXT'        => env('SEARCH_INPUT_TEXT'),
    'CID_STATUS'               => env('CID_STATUS'),
    'CID'                      => env('CID'),
    'POST_UPDATE_DURATION'     => env('POST_UPDATE_DURATION'),
    'NODE_SCRAPER_IP'          => env('NODE_SCRAPER_IP'),
    'DEFAULT_IMAGE'            => env('DEFAULT_IMAGE'),
    'Google_Analytics'         => env('Google_Analytics'),
    'Google_Search_console'    => env('Google_Search_console'),
    'post_content_above'       => env('post_content_above'),
    'bing_image_first'         => env('bing_image_first'),
    'bing_rich_snippet_text'   => env('bing_rich_snippet_text'),
    'google_rich_snippet'      => env('google_rich_snippet'),
    'bing_rich_snippet_link'   => env('bing_rich_snippet_link'),
    'bing_videos_first'        => env('bing_videos_first'),
    'bing_related_keywords'    => env('bing_related_keywords'),
    'post_content_middle'      => env('post_content_middle'),
    'bing_paa'                 => env('bing_paa'),
    'bing_images_second'       => env('bing_images_second'),
    'google_faq'               => env('google_faq'),
    'bing_videos_second'       => env('bing_videos_second'),
    'bing_slider_faq'          => env('bing_slider_faq'),
    'google_related_keywords'  => env('google_related_keywords'),
    'pop_questions'            => env('pop_questions'),
    'bing_tab_faq'             => env('bing_tab_faq'),
    'popular_post'             => env('popular_post'),
    'post_content_after'       => env('post_content_after'),
    'Adsense_pub_id'           => env('Adsense_pub_id'),
    'Bing_API_Key'             => env('Bing_API_Key'),
    'Bing_SERP'                => env('Bing_SERP'),
    'Bing_news'                => env('Bing_news'),
    'WORDPRESS_DB_CAT_ID'      => env('WORDPRESS_DB_CAT_ID'),
];
